apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-runtimes
  namespace: plato
spec:
  selector:
    matchLabels:
      app: log-runtimes
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: log-runtimes
    spec:
      containers:
        - image: dcf21/plato_eas:latest
          name: plato
          resources:
            requests:
              memory: "4Gi"
              cpu: "250m"
          command: [ '/plato_eas/datadir_local/virtualenv/bin/python3' ]
          args: [ '/plato_eas/docker_containers/testbed/transit_search/data_comms_daemon/run_times_output_daemon.py' ]
          env:
            # Use secret in real usage
            - name: dummy
              value: plato
          volumeMounts:
            - name: output-persistent-storage
              mountPath: /plato_eas/datadir_output
            - name: input-persistent-storage
              mountPath: /plato_eas/datadir_input
      volumes:
        - name: output-persistent-storage
          persistentVolumeClaim:
            claimName: output-pvc
        - name: input-persistent-storage
          persistentVolumeClaim:
            claimName: input-pvc
