apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: plato
spec:
  storageClassName: manila-cephfs-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
