apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc
  namespace: plato
spec:
  storageClassName: manila-cephfs-share
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
