apiVersion: apps/v1
kind: Deployment
metadata:
  name: plato
spec:
  selector:
    matchLabels:
      app: plato
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plato
    spec:
      containers:
        - image: plato/eas_all_tdas:v1
          name: plato
          command: [ '/plato_eas/datadir_local/virtualenv/bin/python3' ]
          args: [ '/plato_eas/docker_containers/testbed/transit_search/worker_node/transit_search_worker_v2.py' ]
          env:
            # Use secret in real usage
            - name: dummy
              value: plato
          volumeMounts:
            - name: plato-persistent-storage
              mountPath: /plato_eas/datadir_output
            - name: lightcurves-persistent-storage
              mountPath: /plato_eas/datadir_input
      volumes:
        - name: plato-persistent-storage
          persistentVolumeClaim:
            claimName: datadir-pv-claim
        - name: lightcurves-persistent-storage
          persistentVolumeClaim:
            claimName: lightcurves-pv-claim
