# -*- coding: utf-8 -*-
# lcsg_lc_reader.py

"""
Read the ASCII lightcurves generated by the lightcurve stitching group, and turn them into Lightcurve objects.
"""

import numpy as np
import re
import gzip

from .lightcurve import LightcurveArbitraryRaster


def read_lcsg_lightcurve(filename, gzipped=True, cut_off_time=None):
    """
    Read a lightcurve from an ASCII data file.

    :param filename:
        The filename of the input data file.
    :type filename:
        str
    :param cut_off_time:
        Only read lightcurve up to some cut off time
    :type cut_off_time:
        float
    :return:
        A <LightcurveArbitraryRaster> object.
    """

    times = []
    fluxes = []
    uncertainties = []
    flags = []
    metadata = {
        'filename': filename
    }

    # Look up file open function
    file_opener = gzip.open if gzipped else open

    # Loop over lines of input file
    with file_opener(filename, "rt") as file:
        for line in file:
            # Ignore blank lines and comment lines
            if len(line) == 0 or line[0] == '#':
                # Check for metadata item
                test = re.match(r"# #(.*)=(.*)", line)
                if test is not None:
                    metadata_key = test.group(1).strip()
                    metadata_value = test.group(2).strip()

                    # If metadata value is a float, convert it to a float. Otherwise keep it as string.
                    try:
                        metadata_value = float(metadata_value)
                    except ValueError:
                        pass

                    metadata[metadata_key] = metadata_value

                # ... otherwise ignore this line
                continue

            # Unpack data
            time = float(words[0])
            flux = float(words[1])
            flag = float(words[2])
            uncertainty = 0

            # Check we have not exceeded cut-off time
            if cut_off_time is not None and time > cut_off_time:
                continue

            # Read three columns of data
            words = line.split()
            times.append(time)
            fluxes.append(flux)
            flags.append(flag)
            uncertainties.append(uncertainty)

    # Convert into a Lightcurve object
    lightcurve = LightcurveArbitraryRaster(times=np.asarray(times),
                                           fluxes=np.asarray(fluxes),
                                           uncertainties=np.asarray(uncertainties),
                                           flags=np.asarray(flags),
                                           metadata=metadata
                                           )

    # Return lightcurve
    return lightcurve
