# Use standardised Python environment with EAS pipeline code
FROM plato/eas:v1

# Install EXOTRANS

# Code not yet available

# Write list of available TDAs
RUN echo '["exotrans"]' > /plato_eas/tda_list.json

# Default working directory
WORKDIR /plato_eas
